Repository OpenLiberty/liberty-tools-intellij, pull requests merged in 2023-05, with the labels that each got.

#373 Listen to in-memory document updates to make the cache more responsive to config changes.
  src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/project/AbstractConfigSource.java
  src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/project/PropertiesConfigSource.java
  src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProject.java
  src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProjectManager.java
Labels: bug, enhancement

#386 Check the build file is null before using.
  src/main/java/io/openliberty/tools/intellij/actions/LibertyDevCustomStartAction.java
Labels: language client

#383 Add handling for variable substitution in the form ${ABC}
  src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/operations/completion/LSIncompleteCompletionProposal.java
Labels: language client

#397 Check the initialize future for null before using it.
  src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LanguageServerWrapper.java
Labels: bug, language client

#366 Ensure there is a delay when starting dev mode in debug mode…
  src/main/java/io/openliberty/tools/intellij/util/DebugModeHandler.java
Labels: bug, devmode, automated tests, GUI

#411 Ensure getCodeActions() does not return null and returns a list instead.
  src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanNoArgConstructorQuickFix.java
  src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveAnnotationConflictQuickFix.java
  src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/persistence/PersistenceEntityQuickFix.java
  src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/FilterImplementationQuickFix.java
  src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/HttpServletQuickFix.java
Labels: bug

#423 Report an error if Java 17 (or higher) is not found for launching the language servers.
  src/main/java/io/openliberty/tools/intellij/liberty/lsp/LibertyConfigLanguageServer.java
  src/main/java/io/openliberty/tools/intellij/liberty/lsp/LibertyXmlServer.java
  src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp/JakartaLanguageServer.java
  src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp/MicroProfileServer.java
  src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/server/ProcessStreamConnectionProvider.java
  src/main/java/io/openliberty/tools/intellij/util/Constants.java
Labels: bug, should-fix

#422 Ensure the source compilation unit is from the source field of the context
  src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/ExtendClassProposal.java
  src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/FilterImplementationQuickFix.java
  src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/HttpServletQuickFix.java
  src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/ListenerImplementationQuickFix.java
  src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LSPIJUtils.java
Labels: bug
