Repository OpenLiberty/liberty-tools-intellij, pull requests merged in 2024-10, with the labels that each got.

#999 Casts values to a Number in order to tolerate type conversion from Integer to Double.
  src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/ResourceMethodMultipleEntityParamsQuickFix.java
Labels: bug, language client, future

#1011 Check for null or empty class name in generate OpenAPI annotations
  src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/internal/openapi/java/MicroProfileGenerateOpenAPIOperation.java
Labels: bug

#1008 Set languageId for each of the MicroProfile language mappings.
  src/main/resources/META-INF/lsp.xml
Labels: enhancement, lsp4ij

#1023 Upgrade to LSP4IJ 0.7.0.
  build.gradle
Labels: enhancement
